/*
 * Utools_twitter_tools_api
 * X (Twitter) API for search, Tweets, users, followers, images, media and more. Supports some v1.1 and v2 API endpoints, with more to come in the future!
 *
 * OpenAPI spec version: 1.1
 * Contact: huojiecs@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import java.io.File;
import io.swagger.client.model.ResultT;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TwitterDmsApiToolsApi
 */
@Ignore
public class TwitterDmsApiToolsApiTest {

    private final TwitterDmsApiToolsApi api = new TwitterDmsApiToolsApi();

    
    /**
     * get DMS List
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDMSListV2UsingGETTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String cursor = null;
        ResultT response = api.getDMSListV2UsingGET(apiKey, authToken, ct0, cursor);

        // TODO: test validations
    }
    
    /**
     * get DMS List
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDMSListV2UsingPOSTTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String cursor = null;
        ResultT response = api.getDMSListV2UsingPOST(apiKey, authToken, ct0, cursor);

        // TODO: test validations
    }
    
    /**
     * receiving events
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/get-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDMSUsingGETTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String id = null;
        ResultT response = api.getDMSUsingGET(apiKey, authToken, ct0, id);

        // TODO: test validations
    }
    
    /**
     * receiving events
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/get-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDMSUsingPOSTTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String id = null;
        ResultT response = api.getDMSUsingPOST(apiKey, authToken, ct0, id);

        // TODO: test validations
    }
    
    /**
     * sendDMSMedia events.
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/new-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendDMSMediaUsingGETTest() throws Exception {
        String apiKey = null;
        String attachmentMediaId = null;
        String attachmentType = null;
        String authToken = null;
        String ct0 = null;
        String recipientId = null;
        String text = null;
        String type = null;
        String quickReplyType = null;
        ResultT response = api.sendDMSMediaUsingGET(apiKey, attachmentMediaId, attachmentType, authToken, ct0, recipientId, text, type, quickReplyType);

        // TODO: test validations
    }
    
    /**
     * sendDMSMedia events.
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/new-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendDMSMediaUsingPOSTTest() throws Exception {
        String apiKey = null;
        String attachmentMediaId = null;
        String attachmentType = null;
        String authToken = null;
        String ct0 = null;
        String recipientId = null;
        String text = null;
        String type = null;
        String quickReplyType = null;
        ResultT response = api.sendDMSMediaUsingPOST(apiKey, attachmentMediaId, attachmentType, authToken, ct0, recipientId, text, type, quickReplyType);

        // TODO: test validations
    }
    
    /**
     * sendDMS events.
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/new-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendDMSUsingGETTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String recipientId = null;
        String text = null;
        String type = null;
        ResultT response = api.sendDMSUsingGET(apiKey, authToken, ct0, recipientId, text, type);

        // TODO: test validations
    }
    
    /**
     * sendDMS events.
     *
     * See details https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/new-event&lt;br&gt;  how to get &lt;b&gt;auth_token and ct0&lt;/b&gt;? &lt;br&gt; https://twitter.com/chen22218/status/1722138510680043555 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendDMSUsingPOSTTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        String recipientId = null;
        String text = null;
        String type = null;
        ResultT response = api.sendDMSUsingPOST(apiKey, authToken, ct0, recipientId, text, type);

        // TODO: test validations
    }
    
    /**
     * upload media for DM 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadMediaDMUsingGETTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        File file = null;
        ResultT response = api.uploadMediaDMUsingGET(apiKey, authToken, ct0, file);

        // TODO: test validations
    }
    
    /**
     * upload media for DM 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadMediaDMUsingPOSTTest() throws Exception {
        String apiKey = null;
        String authToken = null;
        String ct0 = null;
        File file = null;
        ResultT response = api.uploadMediaDMUsingPOST(apiKey, authToken, ct0, file);

        // TODO: test validations
    }
    
}
