<?php
/**
 * TwitterUsersApiToolsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Utools_twitter_tools_api
 *
 * X (Twitter) API for search, Tweets, users, followers, images, media and more. Supports some v1.1 and v2 API endpoints, with more to come in the future!
 *
 * OpenAPI spec version: 1.1
 * Contact: huojiecs@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.37
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TwitterUsersApiToolsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TwitterUsersApiToolsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for blocksCreateUsingGET
     *
     * blocks Create.
     *
     */
    public function testBlocksCreateUsingGET()
    {
    }

    /**
     * Test case for blocksCreateUsingPOST
     *
     * blocks Create.
     *
     */
    public function testBlocksCreateUsingPOST()
    {
    }

    /**
     * Test case for blocksDestroyUsingGET
     *
     * blocks Destroy.
     *
     */
    public function testBlocksDestroyUsingGET()
    {
    }

    /**
     * Test case for blocksDestroyUsingPOST
     *
     * blocks Destroy.
     *
     */
    public function testBlocksDestroyUsingPOST()
    {
    }

    /**
     * Test case for getListByUserIdOrScreenNameUsingGET
     *
     * Get List by user_id or screen_name(get-lists-list).
     *
     */
    public function testGetListByUserIdOrScreenNameUsingGET()
    {
    }

    /**
     * Test case for getListByUserIdOrScreenNameUsingPOST
     *
     * Get List by user_id or screen_name(get-lists-list).
     *
     */
    public function testGetListByUserIdOrScreenNameUsingPOST()
    {
    }

    /**
     * Test case for getListMembersByListIdUsingGET
     *
     * Get List Members By ListId (get-lists-members).
     *
     */
    public function testGetListMembersByListIdUsingGET()
    {
    }

    /**
     * Test case for getListMembersByListIdUsingPOST
     *
     * Get List Members By ListId (get-lists-members).
     *
     */
    public function testGetListMembersByListIdUsingPOST()
    {
    }

    /**
     * Test case for getUserByIdOrNameLookUpUsingGET
     *
     * Get user information based on username or id (lookup).
     *
     */
    public function testGetUserByIdOrNameLookUpUsingGET()
    {
    }

    /**
     * Test case for getUserByIdOrNameLookUpUsingPOST
     *
     * Get user information based on username or id (lookup).
     *
     */
    public function testGetUserByIdOrNameLookUpUsingPOST()
    {
    }

    /**
     * Test case for getUserByIdOrNameShowUsingGET
     *
     * Get user information based on username or id (show).
     *
     */
    public function testGetUserByIdOrNameShowUsingGET()
    {
    }

    /**
     * Test case for getUserByIdOrNameShowUsingPOST
     *
     * Get user information based on username or id (show).
     *
     */
    public function testGetUserByIdOrNameShowUsingPOST()
    {
    }

    /**
     * Test case for uerByIdRestIdV2UsingGET
     *
     * Get uerByIdRestId by V2.
     *
     */
    public function testUerByIdRestIdV2UsingGET()
    {
    }

    /**
     * Test case for uerByIdRestIdV2UsingPOST
     *
     * Get uerByIdRestId by V2.
     *
     */
    public function testUerByIdRestIdV2UsingPOST()
    {
    }

    /**
     * Test case for userByScreenNameV2UsingGET
     *
     * Get userByScreenName by V2.
     *
     */
    public function testUserByScreenNameV2UsingGET()
    {
    }

    /**
     * Test case for userByScreenNameV2UsingPOST
     *
     * Get userByScreenName by V2.
     *
     */
    public function testUserByScreenNameV2UsingPOST()
    {
    }

    /**
     * Test case for userTimelineUsingGET
     *
     * Get UserTimeline  tweets info.
     *
     */
    public function testUserTimelineUsingGET()
    {
    }

    /**
     * Test case for userTimelineUsingPOST
     *
     * Get UserTimeline  tweets info.
     *
     */
    public function testUserTimelineUsingPOST()
    {
    }

    /**
     * Test case for userTweetsV2UsingGET
     *
     * Get UserTweets by V2.
     *
     */
    public function testUserTweetsV2UsingGET()
    {
    }

    /**
     * Test case for userTweetsV2UsingPOST
     *
     * Get UserTweets by V2.
     *
     */
    public function testUserTweetsV2UsingPOST()
    {
    }
}
