<?php
/**
 * TwitterLoginGetTokenApiToolsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Utools_twitter_tools_api
 *
 * X (Twitter) API for search, Tweets, users, followers, images, media and more. Supports some v1.1 and v2 API endpoints, with more to come in the future!
 *
 * OpenAPI spec version: 1.1
 * Contact: huojiecs@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.37
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TwitterLoginGetTokenApiToolsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TwitterLoginGetTokenApiToolsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for login2FAUsingGET
     *
     * login by code.
     *
     */
    public function testLogin2FAUsingGET()
    {
    }

    /**
     * Test case for login2FAUsingPOST
     *
     * login by code.
     *
     */
    public function testLogin2FAUsingPOST()
    {
    }

    /**
     * Test case for loginUsingGET
     *
     * login by userName and passwrd.
     *
     */
    public function testLoginUsingGET()
    {
    }

    /**
     * Test case for loginUsingPOST
     *
     * login by userName and passwrd.
     *
     */
    public function testLoginUsingPOST()
    {
    }
}
