/*
 * Utools_twitter_tools_api
 * X (Twitter) API for search, Tweets, users, followers, images, media and more. Supports some v1.1 and v2 API endpoints, with more to come in the future!
 *
 * OpenAPI spec version: 1.1
 * Contact: huojiecs@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.37
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UtoolsTwitterToolsApi);
  }
}(this, function(expect, UtoolsTwitterToolsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UtoolsTwitterToolsApi.TwitterLoginGetTokenApiToolsApi();
  });

  describe('(package)', function() {
    describe('TwitterLoginGetTokenApiToolsApi', function() {
      describe('login2FAUsingGET', function() {
        it('should call login2FAUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for login2FAUsingGET call and complete the assertions
          /*
          var apiKey = "your own apikey";
          var code = "elonmusk";

          instance.login2FAUsingGET(apiKey, code, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UtoolsTwitterToolsApi.ResultT);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.data).to.be.a(Object);
            expect(data.data).to.be();
            expect(data.msg).to.be.a('string');
            expect(data.msg).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('login2FAUsingPOST', function() {
        it('should call login2FAUsingPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for login2FAUsingPOST call and complete the assertions
          /*
          var apiKey = "your own apikey";
          var code = "elonmusk";

          instance.login2FAUsingPOST(apiKey, code, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UtoolsTwitterToolsApi.ResultT);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.data).to.be.a(Object);
            expect(data.data).to.be();
            expect(data.msg).to.be.a('string');
            expect(data.msg).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('loginUsingGET', function() {
        it('should call loginUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for loginUsingGET call and complete the assertions
          /*
          var apiKey = "your own apikey";
          var email = "elonmusk@gmail.com";
          var password = "tesla";
          var screenName = "elonmusk";

          instance.loginUsingGET(apiKey, email, password, screenName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UtoolsTwitterToolsApi.ResultT);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.data).to.be.a(Object);
            expect(data.data).to.be();
            expect(data.msg).to.be.a('string');
            expect(data.msg).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('loginUsingPOST', function() {
        it('should call loginUsingPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for loginUsingPOST call and complete the assertions
          /*
          var apiKey = "your own apikey";
          var email = "elonmusk@gmail.com";
          var password = "tesla";
          var screenName = "elonmusk";

          instance.loginUsingPOST(apiKey, email, password, screenName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UtoolsTwitterToolsApi.ResultT);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.data).to.be.a(Object);
            expect(data.data).to.be();
            expect(data.msg).to.be.a('string');
            expect(data.msg).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
